# Generated by Django 3.2 on 2022-06-27 12:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0018_auto_20220608_1202'),
        ('landlord', '0002_auto_20220627_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('appartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.appartments')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
