# Generated by Django 3.2 on 2022-06-27 08:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0018_auto_20220608_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('unit_price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Appartment',
                'verbose_name_plural': 'Appartments',
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='landlord.landlord')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='AppartmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('appartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_token', to='landlord.appartments')),
            ],
            options={
                'verbose_name': 'Appartment Token',
                'verbose_name_plural': 'Appartment Tokens',
            },
        ),
        migrations.AddField(
            model_name='appartments',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.landlord'),
        ),
    ]
